### ISSUE TITLE
How to retrieve note number/velocity from NoteMessage

### ISSUE THREAD

**Issue by TechPersonYT** [webern/midi_file#13]
I'm trying to parse MIDI files using this library. From what I understand, [NoteMessage](https://docs.rs/midi_file/latest/midi_file/core/struct.NoteMessage.html) contains the note velocity and number, but it doesn't seem to expose those fields as public, or implement any getters. Is there a different way of getting note numbers and velocities, or is this a feature that would need to be added?

My current workaround is sub-optimal to say the least:

```rs
let note_number_str = format!("{:?}", note_message);
let note_number = note_number_str.split("(").collect::<Vec<&str>>()[2].split(")").collect::<Vec<&str>>()[0].parse::<i32>().unwrap();
```

**Comment by TechPersonYT** [comment]
Nevermind, it looks like [parse](https://github.com/webern/midi_file/blob/main/src/core/message.rs#L27) does what I need

**Comment by webern** [comment]
Oops. There are probably a lot of missing getters. I'll try to release a fix for it soon. Impressive workaround...

**Comment by webern** [comment]
v0.0.3 should work better for that.

**Comment by TechPersonYT** [comment]
That's perfect, thanks!
